name: Deploy docs

# the pipe will be run everytime that main branch has a push
on:
  push:
    branches:
      - main

# define steps of pipeline
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # do checkout to get the code
      - name: Checkout
        uses: actions/checkout@v3

      #  install node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # do npm install (made by ci environment, what will isnt modify the package-lock, this is important!)
      - run: npm ci

      # run turborepo build
      - run: npm run build

      # do deploy
      - name: Deploy storybook
        # enter on storybook folder
        working-directory: ./packages/docs
        # run deploy command
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}